### ISSUE TITLE
where is the game?

### ISSUE THREAD

**Issue by seewhy93** [kinzee/MyGame#1]
# where is the game?

**Comment by kinzee** [comment]
fuck you



来自 魅蓝

-------- 原始邮件 --------
发件人：seeeewhy <notifications@github.com>
时间：周五 6月5日 10:02
收件人：kinzee/MyGame <MyGame@noreply.github.com>
主题：[MyGame] where is the game? (#1)

**Comment by seewhy93** [comment]
u r so rude
